Ext.define('app.view.AdminMain',{
	alias:'widget.AdminMain',
	extend:'Ext.grid.Panel',
	title:'用户管理',
	forceFit:true,
	closable:true,
	iconCls:'Userbrown',
	dockedItems:[
		{
			xtype:'toolbar',
			dock:'top',
			padding:'0 10',
			items:[
				{
					xtype:'button',
					id:'adminAdd',
					iconCls:'Useradd',
					text:'添加用户'
				},
				{
					xtype:'button',
					iconCls:'Useredit',
					id:'adminEdit',
					text:'编辑用户',
					disabled:true
				},
				{
					xtype:'button',
					iconCls:'Userdelete',
					id:'adminDelete',
					text:'删除用户',
					disabled:true
				},
				{
					xtype:'button',
					iconCls:'Usergo',
					text:'导出用户'
				},
				{
					xtype:'tbseparator',
					margin:'0 10'
				},
				{
					xtype:'textfield',
					fieldLabel:'搜索',
					labelWidth:30
				},
				{
					xtype:'button',
					iconCls:'Magnifier',
					tooltip:'搜索'
				}
			]
		},
		{
			xtype:'pagingtoolbar',
			dock:'bottom',
			store:'app.store.AdminStore',
			displayInfo:true,
			padding:'0 10'
		}
	],
	selType:'checkboxmodel',
	columns:ColumnFactory.getColumns('app.admin.model.AdminModel'),
    store:'app.store.AdminStore',
    initComponent:function(){
		this.callParent(arguments);
	}
});