Ext.define('app.view.AdminAddForm',{
	extend:'Ext.window.Window',
	alias:'widget.AdminAddForm',
	autoShow:true,
	closable:false,
	modal:true,
	title:'添加用户',
	layout:'fit',
	width:380,
	height:360,
	items:[
		{
			xtype:'form',
			padding:'20px 40px',
			frame:true,
			items:[
				{
					xtype:'textfield',
					fieldLabel:'用户名',
					name:'adminName',
					allowBlank:false,
					msgTarget:'side'
				},
				{
					xtype:'textfield',
					fieldLabel:'密码',
					name:'adminPhone',
					inputType:'password'
				},
				{
					xtype:'textfield',
					fieldLabel:'确认密码',
					name:'adminPhone',
					inputType:'password'
				},
				{
					xtype:'textfield',
					fieldLabel:'邮箱',
					name:'adminEmail'
				},
				{
					xtype:'textfield',
					fieldLabel:'真实姓名',
					name:'adminEmail'
				},
				{
					xtype:'textfield',
					fieldLabel:'手机号码',
					name:'adminEmail'
				},
				{
					xtype:'radiogroup',
					fieldLabel:'是否启用',
					name:'adminAge',
					items:[
						{boxLabel:'禁用',name:'rb',inputValue:'1' },
            			{boxLabel:'启用',name:'rb',inputValue:'0',checked:true}
					]
				},
				{
					xtype:'textarea',
					fieldLabel:'备注'
				}
			]
		}
	],
	buttons:[
		{
			text:'取消',id:'cancle'
		},
		{
			text:'重置',id:'reset'
		},
		{
			text:'添加',id:'save'
		}
	]
});