Ext.define('app.view.FrameMain',{
	extend:'Ext.panel.Panel',
	alias:'widget.FrameMain',
	layout:'border',
	border:false,
	items:[
		{
			xtype:'container',
			region:'north',
			layout:'hbox',
			id:'frameTopContainer',
			height:60,
			items:[
				{
					xtype:'toolbar',
					width:200,
					height:60,
					border:false,
					layout:'fit',
					items:[
						{
							xtype:'image',
							src:'./logo.png'
						}
					]
				},
				{
					xtype:'toolbar',
					height:60,
					flex:1,
					id:'frameTopTools',
					border:false,
					padding:'30 20 0 0',
					layout:'hbox',
					items:[
						{
							xtype:'tbseparator',
							margin:'0 10 0 0'
						},
						{
							xtype:'button',
							iconCls:'Arrowrefresh',
							tooltip:'刷新',
							id:'reFresh'
						},
						{
							xtype:'button',
							iconCls:'Applicationsidecontract',
							tooltip:'折叠菜单',
							id:'foldOnButton'
						},
						{
							xtype:'button',
							iconCls:'Applicationsideexpand',
							tooltip:'展开菜单',
							id:'foldOffButton',
							disabled:true
						},
						{
							xtype:'tbseparator',
							margin:'0 10'
						},
						{
							xtype:'textfield',
							fieldLabel:'搜索',
							labelWidth:30
						},
						{
							xtype:'button',
							iconCls:'Magnifier',
							tooltip:'搜索'
						},
						{
							xtype:'tbfill'
						},
						{
							xtype:'tbtext',
							text:'欢迎您: <b>薛磊</b>'
						},
						{
							xtype:'tbspacer',
							width:'10%'
						},
						{
							xtype:'combobox',
							margin:'0 5',
							fieldLabel:'主题:',
							labelWidth:30,
							width:120,
							queryMode:'local',
						    displayField:'theme',
						    valueField:'css',
						    editable:false,
						    value:'蔚蓝天空',
						    store:'app.store.ThemeStore'
						},
						{
							xtype:'button',
							iconCls:'Lock',
							tooltip:'锁定屏幕'
						},
						{
							xtype:'button',
							iconCls:'Information',
							tooltip:'关于系统'
						},
						{
							xtype:'button',
							iconCls:'Help',
							tooltip:'帮助文档'
						},
						{
							xtype:'button',
							iconCls:'Computergo',
							tooltip:'退出登录'
						}
					]
				}
			]
		},
		{
			xtype:'FrameMenu',
			region:'west',
		},
		{
			xtype:'FrameCenter',
			region:'center'
		},
		{
			xtype:'toolbar',
			region:'south',
			height:25,
			border:false,
			padding:'0 5',
			items:[
				{
					xtype:'image',
					cls:'Usersuit',
					width:16
				},
				{
					xtype:'tbtext',
					text:'当前用户: (系统管理员) <b>薛凯文</b>',
					width:170
				},
				{
					xtype:'tbseparator'
				},
				{
					xtype:'tbfill'
				},
				{
					xtype:'tbtext',
					text:'本系统由<b>kevin</b>开发'
				},
				{
					xtype:'tbfill'
				}
			]
		}
	],
	initComponent:function(){
		this.callParent(arguments);
	}
});