Ext.define('app.view.LoginMain',{
	extend:'Ext.window.Window',
	alias:'widget.LoginMain',
	autoShow:true,
	closable:false,
	title:'登陆',
	width:330,
	height:200,
	layout:'fit',
	iconCls:'Computer',
	draggable:false,
	resizable:false,
	modal:true,
	items:[
		{
			xtype:'form',
			border:false,
			padding:'20',
			frame:'true',
			items:[
				{
					xtype:'textfield',
					fieldLabel:'用户名'
				},
				{
					xtype:'textfield',
					fieldLabel:'密&nbsp;&nbsp;&nbsp;码',
					inputType:'password'
				},
				{
					xtype:'fieldcontainer',
					fieldLabel: '验证码',
					layout:'hbox',
					items:[
						{
							xtype:'textfield',
							width:60
						},
						{
							xtype:'image',
							margin:'0 0 0 20',
							width:70,
							height:22,
							src:'/Admin/Login/verifyCode'
						}
					]
				}
			]
		}
	],
	buttons:[
		{
			text:'重置',iconCls:'Arrowrotateanticlockwise'
		},
		{
			text:'登陆',iconCls:'Accept'
		}
	],
	initComponent:function(){
		this.callParent(arguments);
	}
});